version: 2.1

executors:
  base:
    working_directory: &workdir ~/solidus
    environment: &environment
      DEFAULT_MAX_WAIT_TIME: 10
      SOLIDUS_RAISE_DEPRECATIONS: true
      CIRCLE_TEST_REPORTS: /tmp/test-results
      CIRCLE_ARTIFACTS: /tmp/test-artifacts
    docker:
      - image: &image circleci/ruby:2.5-node-browsers

  postgres:
    working_directory: *workdir
    environment:
      <<: *environment
      DB: postgresql
      DB_HOST: localhost
    docker:
      - image: *image
      - image: jhawthorn/circleci-postgres-fast
        environment:
          POSTGRES_USER: root

jobs:
  rspec-tests:
    executor: postgres
    parallelism: &parallelism 3
    environment:
      RAILS_VERSION: '~> 5.2.0'
    steps:
      - setup
      - test

commands:
  setup:
    steps:
      - run: .circleci/bin/halt-for-doc-only-changes.sh && circleci step halt || true # skip Circle for guides
      - checkout

      - restore_cache:
          keys:
            - solidus-gems-v2-{{ .Branch }}
            - solidus-gems-v2

      - run: |
          bundle install --path=vendor/bundle

      - save_cache:
          key: solidus-gems-v2-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  test:
    steps:
      - run:
          name: Run Tests
          command: ./bin/build-ci test

      - store_artifacts:
          path: /tmp/test-artifacts
          destination: test-artifacts

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results

workflows:
  build:
    jobs:
      - rspec-tests
